= groovy-git

== What is Groovy Git?

A library providing a wrapper around link:https://eclipse.org/jgit/[Eclipse's JGit] for more fluent usage from Groovy.
This allows you to interact easily with link:https://git-scm.com[Git] repositories from general applications
using Groovy or from Gradle builds.

== Where do I get Groovy Git?

To use Groovy Git as a library, add a dependency on it.

[source, groovy]
.build.gradle
----

dependencies {
  compile 'org.xbib:groovy-git:<version>'
}
----

[source, xml]
.pom.xml
----
<!-- make sure you've specified JCenter in your repositories -->
<dependencies>
  <dependency>
    <group>org.xbib</group>
    <artifactId>groovy-git</artifactId>
    <version>...</version>
  </dependency>
</dependencies>
----

To use Groovy Git in a Gradle build, see the documentation for link:gradle.html[org.xbib.gradle.plugin.git].

== How do I use Groovy Git?

First you need to get an instance of Groovy Git, by either link:init.html[initializing] a new repo or
link:open.html[opening] or link:clone.html[cloning] an existing repo.

Once you have a Groovy Git instance, you can use the available operations to inspect or modify the repo.
Each operation has 3 variants, depending on your preference:

[source, groovy]
----
// no arg variant, only applies to operations that don't require input
git.log()

// map argument variant
git.log(includes: ['master', 'other-branch'], excludes: ['old-stuff'], skipCommits: 5)

// closure argument variant
git.log {
  range('1.0.0', '1.5.1')
  maxCommits = 2
}
----

Look in the link:reference.html[reference] documentation for information on each available operation,
it's options, and example usage. Additionally, see the link:authentication.html[authentication] documentation
if you plan to interact with a remote repository.

== Example Usage

In an example like this, using the HTTP protocol, you'll likely need to specify basic auth credentials.
This can be done via system properties or environment variables. SSH access is also supported.
See the link:-authentication.html[authentication] documentation.

[source]
.Environment Variables
----
GIT_USER=somebody
GIT_PASS=myauthtoken
----

[source, groovy]
.gitSample.groovy
----
// get an instance
def git = Git.clone(dir: 'test-repo', uri: 'https://github.com/jprante/groovy-git.git')

// make some changes
new File('test-repo/file.txt') << 'making some changes'
git.add(patterns: ['test-repo/file.txt'])

// make a commit
git.commit(message: 'Adding a new file')

// view the commits
git.log {
  range('origin/master', 'master')
}.each { commit ->
  println "${commit.id} ${commit.shortMessage}"
}

// push to the remote
git.push()

// cleanup after yourself
git.close()
----

include::add.adoc[]

include::apply.adoc[]

include::authentication.adoc[]

include::branch.adoc[]

include::checkout.adoc[]

include::clean.adoc[]

include::clone.adoc[]

include::commit.adoc[]

include::describe.adoc[]

include::fetch.adoc[]

include::gradle.adoc[]

include::head.adoc[]

include::init.adoc[]

include::isAncestorOf.adoc[]

include::log.adoc[]

include::lsremote.adoc[]

include::merge.adoc[]

include::open.adoc[]

include::pull.adoc[]

include::push.adoc[]

include::remote.adoc[]

include::remove.adoc[]

include::reset.adoc[]

include::resolve.adoc[]

include::revert.adoc[]

include::show.adoc[]

include::status.adoc[]

include::tag.adoc[]

