= tag

== Name

tag - Create, list, or delete tag object

== Synopsis

[source, groovy]
----
git.tag.list()
----

[source, groovy]
----
git.tag.add(name: <name>, pointsTo: <commit>, force: <boolean>,
  annotate: <boolean>, message: <msg>, tagger: <person>)
----

[source, groovy]
----
git.tag.remove(names: [<name>, ...])
----

== Description


`git.tag.list()`:: Returns a list of tags (Tag).
`git.tag.add(name: <name>, pointsTo: <commit>, force: <boolean>, annotate: <boolean>, message: <msg>, tagger: <person>)`:: Creates a new tag named `<name>` pointing at `<pointsTo>`.
Returns the created Tag.
`git.tag.remove(names: [<name>, ...])`:: Removes one or more tages. Returns a `List<String>` of tag names removed.

== Options

=== add

name:: (`String`, default `null`) Name of the tag
message:: (`String`, default `null`) Use the given <msg> as the commit message.
tagger:: (`Person`, default `null`) Override the tagger recorded in the tag. This must be a Person.
annotate:: (`boolean`, default `true`) Make an unsigned, annotated tag object
force:: (`boolean`, default `false`) Replace an existing tag with the given name (instead of failing)
pointsTo:: (`Object`, default `null`) Point new tag at this commit. For a more complete list of acceptable inputs, see resolve (specifically the `toRevisionString` method).

=== remove

names:: (`List<Object>`, default `[]`) Names of the tags. For a more complete list of acceptable inputs, see resolve (specifically the `toTagName` method).

== Examples

To list all tags.

[source, groovy]
----
def tags = git.tag.list()
----

Add an annotated tag.

[source, groovy]
----
git.tag.add(name: 'new-tag')
git.tag.add(name: 'new-tag', message: 'Some message')
git.tag.add(name: 'new-tag', annotate: true)
----

Add an unannotated tag.

[source, groovy]
----
git.tag.add(name: 'new-tag', annotate: false)
----

Add a tag starting at a specific commit.

[source, groovy]
----
git.tag.add(name: 'new-tag', pointsTo: 'other-branch')
----

Overwrite an existing tag.

[source, groovy]
----
git.tag.add(name: 'existing-tag', force: true)
----

Remove tags.

[source, groovy]
----
def removedTags = git.tag.remove(names: ['the-tag'])
----

== See Also

- link:https://git-scm.com/docs/git-tag[git-tag]
